In [1]:
## importing Model
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings

In [2]:
data=pd.read_csv('data\\stud.csv')
data.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
X=data.drop(['math_score'],axis=1)
y=data['math_score']

In [4]:
print("Categories in 'gender' variable:     ",end=" " )
print(data['gender'].unique())
print('\n')
print("Categories in 'race_ethnicity' variable:  ",end=" ")
print(data['race_ethnicity'].unique())
print('\n')
print("Categories in'parental level of education' variable:",end=" " )
print(data['parental_level_of_education'].unique())
print('\n')
print("Categories in 'lunch' variable:     ",end=" " )
print(data['lunch'].unique())
print('\n')
print("Categories in 'test preparation course' variable:     ",end=" " )
print(data['test_preparation_course'].unique())

Categories in 'gender' variable:      ['female' 'male']


Categories in 'race_ethnicity' variable:   ['group B' 'group C' 'group A' 'group D' 'group E']


Categories in'parental level of education' variable: ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']


Categories in 'lunch' variable:      ['standard' 'free/reduced']


Categories in 'test preparation course' variable:      ['none' 'completed']

In [5]:
num_feature=X.select_dtypes(exclude='object').columns
cat_feature=X.select_dtypes(include='object').columns

from sklearn.preprocessing import  StandardScaler,OneHotEncoder
from sklearn.compose import  ColumnTransformer

standered_scaler=StandardScaler()
ohe_encoder=OneHotEncoder()

transform= ColumnTransformer(
    [
        ('OneHotEncoder',ohe_encoder,cat_feature),
        ('StandardScaler',standered_scaler,num_feature),
    ]
)

In [6]:
X=transform.fit_transform(X)

In [7]:
X.shape

(1000, 19)

In [8]:
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((800, 19), (200, 19))

In [9]:
from sklearn.metrics import  mean_squared_error,mean_absolute_error,r2_score
def evauate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    score=r2_score(true,predicted)
    return mae,mse,score

In [10]:
from sklearn.linear_model import  LinearRegression,Ridge,Lasso
from sklearn.ensemble import  RandomForestRegressor,AdaBoostRegressor
from sklearn.tree import  DecisionTreeRegressor
from sklearn.neighbors import  KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

models={
    'LinearRegression':LinearRegression(),
    'Ridge':Ridge(),
    'Lasso':Lasso(),
    'RandomForestRegressor':RandomForestRegressor(),
    'Adabost classifier':AdaBoostRegressor(),
    'DecessionTree':DecisionTreeRegressor(),
    'KNN':KNeighborsRegressor(),
    'SVM':SVR(),
    'Xgboost':XGBRegressor()
}

model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    #Train model
    model.fit(X_train,y_train)

    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_mse , model_train_mae, model_train_r2 = evauate_model(y_train, y_train_pred)
    model_test_mse , model_test_mae, model_test_r2 = evauate_model(y_test, y_test_pred)
    

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

     
    print('Model performance for Training set')
    print("- Mean Squared Error: {:.4f}".format(model_train_mse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_mse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

LinearRegression
Model performance for Training set
- Mean Squared Error: 4.2671
- Mean Absolute Error: 28.3487
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.2158
- Mean Absolute Error: 29.1167
- R2 Score: 0.8803
===================================


Ridge
Model performance for Training set
- Mean Squared Error: 4.2650
- Mean Absolute Error: 28.3378
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.2111
- Mean Absolute Error: 29.0563
- R2 Score: 0.8806
===================================


Lasso
Model performance for Training set
- Mean Squared Error: 5.2063
- Mean Absolute Error: 43.4784
- R2 Score: 0.8071
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.1579
- Mean Absolute Error: 42.5064
- R2 Score: 0.8253
===================================


RandomForestRegressor
Model performance for Training set
- Mean Squared Error: 1.8393
- Mean Absolute Error: 5.3937
- R2 Score: 0.9761
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.6277
- Mean Absolute Error: 35.9414
- R2 Score: 0.8523
===================================


Adabost classifier
Model performance for Training set
- Mean Squared Error: 4.7649
- Mean Absolute Error: 33.9619
- R2 Score: 0.8494
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.8120
- Mean Absolute Error: 37.8854
- R2 Score: 0.8443
===================================


DecessionTree
Model performance for Training set
- Mean Squared Error: 0.0187
- Mean Absolute Error: 0.0781
- R2 Score: 0.9997
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.3750
- Mean Absolute Error: 64.5050
- R2 Score: 0.7349
===================================


KNN
Model performance for Training set
- Mean Squared Error: 4.5167
- Mean Absolute Error: 32.5776
- R2 Score: 0.8555
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.6210
- Mean Absolute Error: 52.6066
- R2 Score: 0.7838
===================================


SVM
Model performance for Training set
- Mean Squared Error: 4.8692
- Mean Absolute Error: 43.2570
- R2 Score: 0.8081
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.4015
- Mean Absolute Error: 66.0420
- R2 Score: 0.7286
===================================


Xgboost
Model performance for Training set
- Mean Squared Error: 0.6875
- Mean Absolute Error: 1.0146
- R2 Score: 0.9955
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.0577
- Mean Absolute Error: 41.9037
- R2 Score: 0.8278
===================================